### ISSUE TITLE
Controls being removed from underneath the module seem to permanently disturb it

### ISSUE THREAD

**Issue by linxcat** [KayelGee/control-concealer#7]
Sometimes when a module is updated, the names of certain controls change. Other times, such as here where I changed a setting, they aren't added to the tool palette. In these cases, the  module is complaining that an expected control is missing, but this never goes away, even after toggling edit mode on and off like the error suggests. It will reappear on every reload. I attempted disabling and enabling the module, and uninstalling it completely and reinstalling it. Both resulted in the problem remaining once it was enabled again.

Here's the console error for Combat Numbers as an example:
`Control concealer | couldn't find:  
{name: "combatNumbers", title: "COMBATNUMBERS.CONTROLS.title", icon: "fas fa-hashtag", layer: "CombatNumberLayer", tools: Array(0)}
icon: "fas fa-hashtag"
layer: "CombatNumberLayer"
name: "combatNumbers"
title: "COMBATNUMBERS.CONTROLS.title"
tools: []
__proto__: Object`

**Comment by KayelGee** [comment]
I can't really reproduce what you're seeing.
Is your console maybe throwing other errors aswell that prevent my module to save the changes?

**Comment by KayelGee** [comment]
If the error persists then you can clear the flags with this code: `game.user.update({['flags.-=control-concealer']:null})`

**Comment by linxcat** [comment]
That completely fixed the problem. I checked for errors on save first, though. There were none. For your future though, this is most likely to happen when module updates change names, types, or possibly placement? Not sure. Thank you for the fix, though.

**Comment by KayelGee** [comment]
The message that you saw was because I'm actually checking if the controls change in some way. If they only change placement it'll find the new placement without an error. If anything else chnages and I can't match what was saved then I'll show the error message. When you enter edit mode and leave it then it'll save everything again, overwriting what has been previously saved, which should solve the issue.
It's strange that it didn't work, maybe combat numbers is doing something special. I'll have to check that.

**Comment by linxcat** [comment]
I also got it with paralaxia, and one other mod that I now forget
